name: test

on:
  push:
    paths:
      - infra/**
  schedule:
    - cron: "00 00 * * 3"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        terraform-version: [1.9.8]
    runs-on: ${{ matrix.platform }}
    environment: ci
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: ${{secrets.ARM_USE_OIDC}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          version: v0.57.0
      - name: Run CI test
        run: |
          cd infra
          make ci-test
